MEN - Z75 MDIS Driver - Z75 MDIS Driver: z75_simp.c File Reference
Z75 MDIS Driver
Z75 MDIS Driver: z75_simp.c File Reference
z75_simp.c File Reference
Simple example program for the Z75 driver.
Functions
static void PrintError (char *info)
Print MDIS error message.
static void __MAPILIB SigHandler (u_int32 sigCode)
Signal Handler.
int main (int argc, char *argv[])
Program main function.
Variables
static const char RCSid [] = "$Id: z75__simp_8c.html,v 1.5 2010/04/22 11:11:33 amorbach Exp $"
Detailed Description
Simple example program for the Z75 driver.
Author:
rla
Date
2010/04/22 11:06:51
Revision
1.3
Reads the frequency or monitors frequency
Required: libraries: mdis_api
Preprocessor Switches:
(none)
Function Documentation
int main (int argc, char * argv[])
Program main function.
Parameters:
argc IN argument counter
argv IN argument vector
Returns:
success (0) or error (1)
Examples:
z75_simp.c.
References PrintError(), SigHandler(), Z075_A_LOWER_LTD, Z075_A_UPPER_LTD, Z075_AUTO_MODE, Z075_CLR_SIG_LOWER, Z075_CLR_SIG_UPPER, Z075_FREQUENCY, Z075_RESOLUTION, Z075_SET_SIG_LOWER, Z075_SET_SIG_UPPER, and Z075_START_MEAS.
static void PrintError (char * info) [static]
Print MDIS error message.
Parameters:
info IN info string
Examples:
z75_simp.c.
Referenced by main().
static void __MAPILIB SigHandler (u_int32 sigCode) [static]
Signal Handler.
Parameters:
sigCode IN signal Code of received signal
Examples:
z75_simp.c.
Referenced by main().
Variable Documentation
const char RCSid[] = "$Id: z75__simp_8c.html,v 1.5 2010/04/22 11:11:33 amorbach Exp $" [static]
Examples:
z75_simp.c.