MEN - Z75 MDIS Driver - Z75 MDIS Driver: z75_drv.c File Reference
Z75 MDIS Driver
Z75 MDIS Driver: z75_drv.c File Reference
z75_drv.c File Reference
Low-level driver for Z75 module.
Functions
void Z75_GetEntry (LL_ENTRY *drvP)
Initialize driver's jump table.
static int32 Z75_Init (DESC_SPEC *descP, OSS_HANDLE *osHdl, MACCESS *ma, OSS_SEM_HANDLE *devSemHdl, OSS_IRQ_HANDLE *irqHdl, LL_HANDLE **llHdlP)
Allocate and return low-level handle, initialize hardware.
static int32 Z75_Exit (LL_HANDLE **llHdlP)
De-initialize hardware and clean up memory.
static int32 Z75_Read (LL_HANDLE *llHdl, int32 ch, int32 *valueP)
Read a value from the device.
static int32 Z75_Write (LL_HANDLE *llHdl, int32 ch, int32 value)
Description: Write a value to the device.
static int32 Z75_SetStat (LL_HANDLE *llHdl, int32 code, int32 ch, INT32_OR_64 value32_or_64)
Set the driver status.
static int32 Z75_GetStat (LL_HANDLE *llHdl, int32 code, int32 ch, INT32_OR_64 *value32_or_64P)
Get the driver status.
static int32 Z75_BlockRead (LL_HANDLE *llHdl, int32 ch, void *buf, int32 size, int32 *nbrRdBytesP)
Read a data block from the device.
static int32 Z75_BlockWrite (LL_HANDLE *llHdl, int32 ch, void *buf, int32 size, int32 *nbrWrBytesP)
Write a data block from the device.
static int32 Z75_Irq (LL_HANDLE *llHdl)
Interrupt service routine.
static int32 Z75_Info (int32 infoType,...)
Get information about hardware and driver requirements.
static char * Ident (void)
Return ident string.
static int32 Cleanup (LL_HANDLE *llHdl, int32 retCode)
Close all handles, free memory and return error code.
static int32 GetFreq (LL_HANDLE *llHdl, u_int32 *freqP)
Read value of Result register and calculate the measured frequency if a new values is measured.
static void automatedTsk (void *hdl)
This task is called from OSS_Alarm if time llHdl->realMsec elapsed.
static int checkRange (u_int32 clk, u_int32 per)
This routine evaluates the calculation range.
Detailed Description
Low-level driver for Z75 module.
Author:
rla
Date
2010/04/22 11:06:07
Revision
1.4
Required: OSS, DESC, DBG, ID libraries
Preprocessor Switches:
_ONE_NAMESPACE_PER_DRIVER_
Function Documentation
static void automatedTsk (void * hdl) [static]
This task is called from OSS_Alarm if time llHdl->realMsec elapsed.
Parameters:
hdl IN Low-level handle
References GetFreq(), LL_HANDLE::lowLimit, LL_HANDLE::lowSigIdP, LL_HANDLE::osHdl, LL_HANDLE::startFlag, LL_HANDLE::upLimit, and LL_HANDLE::upSigIdP.
Referenced by Z75_SetStat().
static int checkRange (u_int32 clk, u_int32 per) [static]
This routine evaluates the calculation range.
Parameters:
clk IN FPGA system core clock
per IN period value
Referenced by GetFreq().
static int32 Cleanup (LL_HANDLE * llHdl, int32 retCode) [static]
Close all handles, free memory and return error code.
Warning:
The low-level handle is invalid after this function is called.
Parameters:
llHdl IN Low-level handle
retCode IN Return value
Returns:
IN retCode
References DBH, LL_HANDLE::descHdl, LL_HANDLE::memAlloc, and LL_HANDLE::osHdl.
Referenced by Z75_Exit(), and Z75_Init().
static int32 GetFreq (LL_HANDLE * llHdl, u_int32 * freqP) [static]
Read value of Result register and calculate the measured frequency if a new values is measured.
Parameters:
llHdl IN Low-level handle
freqP IN pointer to store frequency value
Returns:
IN 0 if value could be determined or Error code
References checkRange(), DBH, LL_HANDLE::fpgaSysClk, LL_HANDLE::ma, Z075_CTRL_STS_ADDR_OFFSET, Z075_RES_MEAS_TIME_MSK, Z075_RES_NEW_VALUE_MSK, Z075_RES_PERIOD_MSK, Z075_RESULT_ADDR_OFFSET, Z075_STS_HIGH_MSK, and Z075_STS_LOW_MSK.
Referenced by automatedTsk(), and Z75_GetStat().
static char* Ident (void) [static]
Return ident string.
Returns:
Pointer to ident string
Referenced by Z75_Init().
static int32 Z75_BlockRead (LL_HANDLE * llHdl, int32 ch, void * buf, int32 size, int32 * nbrRdBytesP) [static]
Read a data block from the device.
Parameters:
llHdl IN Low-level handle
ch IN Current channel
buf IN Data buffer
size IN Data buffer size
nbrRdBytesP OUT Number of read bytes
Returns:
0 On success or error code
Referenced by Z75_GetEntry().
static int32 Z75_BlockWrite (LL_HANDLE * llHdl, int32 ch, void * buf, int32 size, int32 * nbrWrBytesP) [static]
Write a data block from the device.
Parameters:
llHdl IN Low-level handle
ch IN Current channel
buf IN Data buffer
size IN Data buffer size
nbrWrBytesP OUT Number of written bytes
Returns:
0 On success or error code
Referenced by Z75_GetEntry().
static int32 Z75_Exit (LL_HANDLE ** llHdlP) [static]
De-initialize hardware and clean up memory.
The function deinitializes all channels by setting them to ???. The interrupt is disabled.
Parameters:
llHdlP IN Pointer to low-level driver handle
Returns:
0 On success or error code
References Cleanup(), DBH, LL_HANDLE::ma, and Z075_CTRL_STS_ADDR_OFFSET.
Referenced by Z75_GetEntry().
void Z75_GetEntry (LL_ENTRY * drvP)
Initialize driver's jump table.
Parameters:
drvP OUT Pointer to the initialized jump table structure
References Z75_BlockRead(), Z75_BlockWrite(), Z75_Exit(), Z75_GetStat(), Z75_Info(), Z75_Init(), Z75_Irq(), Z75_Read(), Z75_SetStat(), and Z75_Write().
static int32 Z75_GetStat (LL_HANDLE * llHdl, int32 code, int32 ch, INT32_OR_64 * value32_or_64P) [static]
Get the driver status.
The driver supports these status codes in addition to the standard codes (see mdis_api.h).
Parameters:
llHdl IN low-level handle
code IN status code
ch IN current channel
value32_or_64P IN pointer to block data structure (M_SG_BLOCK) for block status codes
value32_or_64P OUT data pointer or pointer to block data structure (M_SG_BLOCK) for block status codes
Returns:
0 On success or error code
References LL_HANDLE::autoMode, CH_NUMBER, LL_HANDLE::dbgLevel, DBH, GetFreq(), LL_HANDLE::irqCount, LL_HANDLE::lowLimit, LL_HANDLE::res, LL_HANDLE::startFlag, LL_HANDLE::upLimit, Z075_A_LOWER_LTD, Z075_A_UPPER_LTD, Z075_AUTO_MODE, Z075_FREQUENCY, Z075_RESOLUTION, and Z075_START_MEAS.
Referenced by Z75_GetEntry().
static int32 Z75_Info (int32 infoType, ...) [static]
Get information about hardware and driver requirements.
The following info codes are supported:
  Code                      Description
  ------------------------  -----------------------------
  LL_INFO_HW_CHARACTER      Hardware characteristics
  LL_INFO_ADDRSPACE_COUNT   Number of required address spaces
  LL_INFO_ADDRSPACE         Address space information
  LL_INFO_IRQ               Interrupt required
  LL_INFO_LOCKMODE          Process lock mode required
The LL_INFO_HW_CHARACTER code returns all address and data modes (ORed) which are supported by the hardware (MDIS_MAxx, MDIS_MDxx).
The LL_INFO_ADDRSPACE_COUNT code returns the number of address spaces used by the driver.
The LL_INFO_ADDRSPACE code returns information about one specific address space (MDIS_MAxx, MDIS_MDxx). The returned data mode represents the widest hardware access used by the driver.
The LL_INFO_IRQ code returns whether the driver supports an interrupt routine (TRUE or FALSE).
The LL_INFO_LOCKMODE code returns which process locking mode the driver needs (LL_LOCK_xxx).
Parameters:
infoType IN Info code
... IN Argument(s)
Returns:
0 On success or error code
References ADDRSPACE_COUNT, ADDRSPACE_SIZE, and USE_IRQ.
Referenced by Z75_GetEntry().
static int32 Z75_Init (DESC_SPEC * descP, OSS_HANDLE * osHdl, MACCESS * ma, OSS_SEM_HANDLE * devSemHdl, OSS_IRQ_HANDLE * irqHdl, LL_HANDLE ** llHdlP) [static]
Allocate and return low-level handle, initialize hardware.
The function initializes all channels with the definitions made in the descriptor. The interrupt is disabled.
The function decodes these descriptor entries in addition to the general descriptor keys.
Parameters:
descP IN Pointer to descriptor data
osHdl IN OSS handle
ma IN HW access handle
devSemHdl IN Device semaphore handle
irqHdl IN IRQ handle
llHdlP OUT Pointer to low-level driver handle
Returns:
0 On success or error code
References Cleanup(), DBG_MYLEVEL, DBH, Ident(), Z075_CTRL_STS_ADDR_OFFSET, Z075_DESC_DEF_RESOLUTION, Z075_DESC_DEF_SYSCLK, Z075_DESC_DEF_UPLTD, and Z075_DESC_DEV_LOWLTD.
Referenced by Z75_GetEntry().
static int32 Z75_Irq (LL_HANDLE * llHdl) [static]
Interrupt service routine.
The interrupt is triggered when ??? occurs.
If the driver can detect the interrupt's cause it returns LL_IRQ_DEVICE or LL_IRQ_DEV_NOT, otherwise LL_IRQ_UNKNOWN.
Parameters:
llHdl IN Low-level handle
Returns:
LL_IRQ_DEVICE IRQ caused by device LL_IRQ_DEV_NOT IRQ not caused by device LL_IRQ_UNKNOWN Unknown
References DBH, and LL_HANDLE::irqCount.
Referenced by Z75_GetEntry().
static int32 Z75_Read (LL_HANDLE * llHdl, int32 ch, int32 * valueP) [static]
Read a value from the device.
The function reads the ??? state of the current channel.
If the channel's direction is not configured as input the function returns an ERR_LL_ILL_DIR error.
Parameters:
llHdl IN Low-level handle
ch IN Current channel
valueP OUT Read value
Returns:
0 On success or error code
Referenced by Z75_GetEntry().
static int32 Z75_SetStat (LL_HANDLE * llHdl, int32 code, int32 ch, INT32_OR_64 value32_or_64) [static]
Set the driver status.
The driver supports these status codes in addition to the standard codes (see mdis_api.h).
Parameters:
llHdl IN low-level handle
code IN status code
ch IN current channel
value32_or_64 IN data or pointer to block data structure (M_SG_BLOCK) for block status codes
Returns:
0 On success or error code
References LL_HANDLE::alarmHdl, automatedTsk(), LL_HANDLE::autoMode, LL_HANDLE::dbgLevel, DBH, LL_HANDLE::irqCount, LL_HANDLE::lowLimit, LL_HANDLE::lowSigIdP, LL_HANDLE::ma, LL_HANDLE::osHdl, LL_HANDLE::res, LL_HANDLE::startFlag, LL_HANDLE::upLimit, LL_HANDLE::upSigIdP, Z075_A_LOWER_LTD, Z075_A_UPPER_LTD, Z075_AUTO_MODE, Z075_CLR_SIG_LOWER, Z075_CLR_SIG_UPPER, Z075_CTRL_STS_ADDR_OFFSET, Z075_RESOLUTION, Z075_SET_SIG_LOWER, Z075_SET_SIG_UPPER, Z075_START_MEAS, Z075_STS_EN_MSK, and Z075_STS_RES_MSK.
Referenced by Z75_GetEntry().
static int32 Z75_Write (LL_HANDLE * llHdl, int32 ch, int32 value) [static]
Description: Write a value to the device.
The function writes a value to the current channel.
If the channel's direction is not configured as output the function returns an ERR_LL_ILL_DIR error.
Parameters:
llHdl IN Low-level handle
ch IN Current channel
value IN Read value
Returns:
0 on success or error code
Referenced by Z75_GetEntry().